server:
  port: 8081
spring:
  main:
    banner-mode: off
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://192.168.50.210:5432/acc_db
    username: acc
    password: acc
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  config: logback-spring.xml

