server:
  port: 8081
spring:
  main:
    banner-mode: off
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8082"
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  config: classpath:logback-spring.xml


