version: '3'
services:

  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=1
      - REDIS_USER=1
      - REDIS_USER_PASSWORD=1
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  db:
    image: postgres:latest
    container_name: acc_db
    environment:
      POSTGRES_DB: acc_db
      POSTGRES_USER: acc
      POSTGRES_PASSWORD: acc
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U acc -d acc" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_acc_db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "acc@acc.com"
      PGADMIN_DEFAULT_PASSWORD: "acc"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
