version: '3'
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    restart: always
  config-service:
    container_name: config-service
    build:
      context: .
      dockerfile: config-service/Dockerfile
    ports:
      - "8082:8082"
    restart: always
  ssh_server:
    image: nginx
    command: /bin/bash -c "apt-get update && apt-get install -y openssh-server && service ssh start && /bin/bash"
    ports:
    - "2222:22"
  db:
    image: postgres:latest
    container_name: acc_db
    environment:
      POSTGRES_USER: acc
      POSTGRES_PASSWORD: acc
      POSTGRES_DB: acc_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U acc -d acc" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_acc_db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "acc@acc.com"
      PGADMIN_DEFAULT_PASSWORD: "acc"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
