version: '3'
services:
  db:
    image: postgres:latest
    container_name: acc_db
    environment:
      POSTGRES_USER: acc
      POSTGRES_PASSWORD: acc
      POSTGRES_DB: acc_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U acc -d acc" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_acc_db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "acc@acc.com"
      PGADMIN_DEFAULT_PASSWORD: "acc"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
