server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  config: logback-spring.xml

