server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true