server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://192.168.50.210:8081
              predicates:
                - Path=/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://192.168.50.210:8761/eureka
    enabled: true