server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/**
            - id: cards-service
              uri: http://localhost:8082
              predicates:
                - Path=/**
            - id: loans-service
              uri: http://localhost:8083
              predicates:
                - Path=/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:logback-spring.xml

