server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      retry:
        max-retries-on-next-service-instance: 3
        max-retries-on-same-service-instance: 3
    gateway:
      server:
        webmvc:
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/**
            - id: CARDS-SERVICE
              uri: lb://CARDS-SERVICE
              predicates:
                - Path=/**
            - id: LOANS-SERVICE
              uri: lb://LOANS-SERVICE
              predicates:
                - Path=/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:logback-spring.xml

