spring:
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  config: classpath:logback-spring.xml