server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://192.168.50.69:5432/acc
    username: acc
    password: acc
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

