spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:catcell4787-cmd/jcb-config.git
          clone-on-start: true
          default-label: main
          search-paths: '{application}/{profile}'
server:
  port: 8082

